# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from preguntas import Ui_preguntas

class Ui_SecondWindow(object):


    def pasarAPreguntas(self, title, subtitle):

        f = open('data.txt', 'a')
        f.write(title + '\n')
        f.write(subtitle + '\n')
        f.close()

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_preguntas()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.pasarAPreguntas(title= 'AAAC', subtitle='Anaheim'))
        self.pushButton_3.setGeometry(QtCore.QRect(110, 110, 201, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.pasarAPreguntas(title= 'ACSR', subtitle='Starling'))
        self.pushButton_4.setGeometry(QtCore.QRect(510, 110, 201, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        SecondWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SecondWindow)
        self.statusbar.setObjectName("statusbar")
        SecondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "MainWindow"))
        self.label_2.setText(_translate("SecondWindow", "AAAC"))
        self.label_3.setText(_translate("SecondWindow", "ACSR"))
        self.pushButton_3.setText(_translate("SecondWindow", "ANAHEIM"))
        self.pushButton_4.setText(_translate("SecondWindow", "STARLING"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
